# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    # Generate summary report
    summaryContent="This is a summary report."
    echo "$summaryContent" > summary.md

    # Upload the summary file
    ls -al
    echo "##vso[task.uploadsummary]$(Build.SourcesDirectory)/summary.md"
    echo "##vso[task.uploadsummary]$(Build.SourcesDirectory)/summary-test.md"
    echo "##vso[task.uploadsummary]$(Build.SourcesDirectory)/report.html"
  displayName: 'Run a multi-line script'

- task: publishhtmlreport@1
  inputs:
    htmlType: 'genericHTML'
    htmlPath: '$(Build.SourcesDirectory)/report-two.html'
